[project]
name = "designs"
version = "0.1.0"
description = "Add a short description here"
authors = ["V <nandithebull@outlook.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
flask = "3.0.0.*"
python = "3.12.0.*"
pip = "23.3.1.*"
